package com.example.labparcial01;

import androidx.appcompat.app.AppCompatActivity;
import androidx.cardview.widget.CardView;
import androidx.recyclerview.widget.AsyncDifferConfig;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.os.AsyncTask;
import android.os.Bundle;
import android.view.View;
import android.widget.EditText;
import android.widget.ProgressBar;
import android.widget.RelativeLayout;

import java.util.ArrayList;
import java.util.List;

public class Lista_imagenes extends AppCompatActivity {

    private RecyclerView recyclerViewCanciones;
    private CustomAdapter customAdapterCantante;
    private CardView cardView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_lista_imagenes);

        enlazarViews();

        new Task2().execute();

    }

    private void enlazarViews(){
        cardView = (CardView) findViewById(R.id.cardViewV);
    }

    private void enviarDatos(){

        recyclerViewCanciones = (RecyclerView) findViewById(R.id.RecyclerViewCanciones);
        recyclerViewCanciones.setLayoutManager(new LinearLayoutManager(this));
        customAdapterCantante = new CustomAdapter(obtenerCanciones());
        recyclerViewCanciones.setAdapter(customAdapterCantante);

    }

    private class Task2 extends AsyncTask<String,Void,String>{

        @Override
        protected String doInBackground(String... strings) {

                enviarDatos();

            return null;
        }
    }

    public List<Canciones> obtenerCanciones(){
        List<Canciones> canciones = new ArrayList<>();
        canciones.add(new Canciones("Like a Rolling Stone", "Bob Dylan", "«Like a Rolling Stone» es una canción de 1965 del cantautor estadounidense Bob Dylan. Su letra reivindicativa proviene de un poema que Dylan escribió en junio de dicho año, cuando regresó extenuado de una gira agotadora por Inglaterra. Después de que se revisara la letra numerosas veces, «Like a Rolling Stone» se grabó unas pocas semanas después en parte de las sesiones para su siguiente álbum de estudio, Highway 61 Revisited. Durante una preproducción difícil de dos días, Dylan luchó para hallar la esencia de la canción; se grabó un demo carente de éxito en compás de 3/4. Se hizo un avance cuando se intentó grabar en formato de rock 4/4 en tiempo medio y el músico de sesión novato Al Kooper improvisó el riff de órgano por el que la canción es conocida. Sin embargo, Columbia Records no estaba satisfecha con ella debido a sus seis minutos de duración y su sonido eléctrico y pesado, por lo que no estaba segura sobre su lanzamiento. Solo cuando un mes después se filtró una copia del tema y disc jockeys influyentes la escucharon se puso a la venta como sencillo. Aunque las emisoras de radio eran reacias a transmitir una canción tan larga, «Like a Rolling Stone» alcanzó el segundo puesto en las listas de Estados Unidos y se convirtió en un éxito internacional.\n" +
                "\n" +
                "Se ha descrito el tema como revolucionario en su combinación de diferentes elementos musicales, el sonido jovial y cínico de la voz de Dylan y la asertividad de la pregunta del estribillo: How does it feel? («¿Qué se siente?»). «Like a Rolling Stone» transformó la carrera de Dylan y todavía se la considera una de las composiciones más influyentes en la música popular de la posguerra. Desde su lanzamiento fue un hito tanto en la música como en la cultura popular que elevó la figura de Dylan hasta volverla icónica. Artistas variados como The Jimi Hendrix Experience, The Rolling Stones, The Wailers y Green Day realizaron versiones de la canción. En castellano, podemos encontrar la versión del grupo Mamá (Cómo lo ves) y por el grupo M-Clan (Sin Rumbo Y Sin Dirección). Además, la revista Rolling Stone la colocó en el número 1 de su lista de las «500 mejores canciones de todos los tiempos»",1965,1,R.drawable.likearollingstone));
        canciones.add(new Canciones("(I Can't Get No) Satisfaction", "The Rolling Stones","«(I Can't Get No) Satisfaction» en españolː «(No puedo obtener ninguna) satisfacción»— es un sencillo lanzado por la banda británica de rock The Rolling Stones en 1965. La canción fue compuesta por los líderes de la agrupación, el cantante Mick Jagger y el guitarrista Keith Richards, y grabada en los estudios RCA en Hollywood a mediados de mayo de 1965, durante su gira por Norteamérica, bajo la producción de su mánager Andrew Loog Oldham. La canción se lanzó en los Estados Unidos el 6 de junio de 1965, pero también se incluyó en el álbum Out of Our Heads, que salió a la venta en julio de ese mismo año. «Satisfaction», cuyo riff es uno de los más famosos de la historia del rock, dio a la banda su primer número uno en los Estados Unidos.[cita requerida] La versión inglesa del Out of Our Heads no incluía «Satisfaction», ya que la canción se lanzó en formato sencillo el 20 de agosto de ese año (no era una práctica ortodoxa en el Reino Unido incluir canciones ya lanzadas como sencillo en los álbumes). El sencillo también alcanzó el número uno, siendo el cuarto número uno de la banda en el Reino Unido. Esta composición estableció a la banda en la escena musical mundial y se convirtió en su primer éxito a nivel global.4\u200B\n" +
                "\n" +
                "Jagger alabó el tema porque supuso la popularización de los Stones y sugirió que su éxito se debía a su reflejo del «espíritu de los tiempos». La canción escrita casi en su totalidad por el vocalista es un retrato de un adolescente atormentado por una frustración general,5\u200B en ella se refleja «el mundo de los sesenta», las esperanzas de su generación y el cinismo de la época.6\u200B Su referencia a las relaciones sexuales y los tintes anticapitalistas del corte causaron gran revuelo en la sociedad de esa década, misma que fue visto como «un ataque al statu quo».7\u200B Es considerada por la crítica como la mejor grabación de la banda8\u200B y una de las mejores de la música contemporánea.9\u200B10\u200B11\u200B Según el sitio agregador de listas Acclaimed Music, es la 5.ª canción más aclamada por los críticos de todos los tiempos.12\u200B La revista Rolling Stone la colocó como la número 2 en su lista de Las 500 canciones más grandes de la historia,13\u200B mientras que la cadena televisiva estadounidense VH1 la puso en el número 1 en su lista de Las 100 canciones más grandes de rock & roll.14\u200B En el 2006 un jurado compuesto por expertos en preservación de música y sonido de los Estados Unidos la anexó en el Registro Nacional de Grabaciones de la Biblioteca del Congreso de Estados Unidos debido a su «relevancia cultural o histórica» en la vida norteamericana.15\u200B A su vez ha sido versionada por varios artistas entre los que destacan Britney Spears, Otis Redding, Devo y Gloria Trevi,16\u200B entre otros",1965 ,2,R.drawable.icantgetno));
        canciones.add(new Canciones("Imagine", "John Lennon", "«Imagine» es una canción compuesta e interpretada por el músico inglés John Lennon y escrita por Yoko Ono y él1\u200B a principios de 1971.2\u200B Si bien el sello discográfico Apple Records distribuyó la canción a partir de octubre de ese año en Estados Unidos,3\u200B esta no estuvo disponible en Reino Unido hasta 1975.4\u200B Se trata de una balada de piano del género soft rock5\u200B6\u200B7\u200B cuya letra hace alusión a una variedad de conceptos, aunque primordialmente promueve la idea de que «todos somos una nación, un mundo y una sociedad».2\u200B En 1987 se estrenó un videoclip para promocionar la canción, bajo la dirección de Zbigniew Rybczyński.8\u200B\n" +
                "\n" +
                "Desde su lanzamiento se han vendido alrededor de cinco millones de copias físicas del sencillo, y hasta 2018 se han distribuido más de cuatro millones de copias digitales,9\u200B con lo que se le considera el tema más exitoso en la trayectoria musical de Lennon como solista.3\u200B10\u200B Si bien algunos críticos como John Blaney y Chris Ingham tuvieron opiniones desfavorables sobre su letra,11\u200B12\u200B en términos generales la canción ha obtenido reseñas positivas y es catalogada como «el mayor regalo musical para el mundo» por parte de Lennon,2\u200B así como «la más reverenciada de las canciones post Beatles»,13\u200B además de hacerse acreedora a ciertos reconocimientos como un galardón del premio del Salón de la Fama de los Grammy,14\u200B entre otros.\n" +
                "\n" +
                "La canción ha sido interpretada en situaciones de violencia, ya que «captura la fragilidad de nuestra esperanza tras un suceso violento o destructivo ... aunque [también] revela su tenacidad»;15\u200B por ejemplo, el pianista alemán Davide Martello interpretó una versión tras los atentados de París de noviembre de 201516\u200B17\u200B Asimismo, varios otros músicos y agrupaciones han llevado a cabo otras versiones del tema, entre los cuales se incluyen Elton John,18\u200B Queen,19\u200B David Bowie,20\u200B Madonna21\u200B y Lady Gaga.",1971,3,R.drawable.imagine));
        canciones.add(new Canciones("What's Going On", "Marvin Gaye", "What's Going On -En español: Lo que está pasando- es el undécimo álbum de estudio del cantante estadounidense de soul Marvin Gaye. Lanzado el 21 de mayo de 1971, significó el inicio de una nueva tendencia en la música soul. Con letras intimistas acerca del abuso de drogas, la pobreza y la guerra de Vietnam, el álbum fue una sensación inmediata y ha permanecido como un clásico del soul.\n" +
                "\n" +
                "Constantemente es nombrado en encuestas como una de las grabaciones fundamentales en la historia de la música pop y es considerado uno de los discos más importantes de todos los tiempos. Ocupa el 1 lugar en la lista de Rolling Stone de los 500 mejores álbumes de todos los tiempos publicada en 2003 tras una reedición en 2020, y en 1999 una encuesta de críticos publicada por el diario británico Guardian/Observer lo nombró como \"El álbum más grande del siglo XX\".\n" +
                "\n" +
                "El productor fue el propio Marvin Gaye. What's Going On es un álbum-concepto que incluye nueve canciones (todas conectadas excepto la primera) como si fuera el punto de vista de un veterano de la guerra de Vietnam que regresa a Estados Unidos, el país por el cual ha estado peleando, y no ve más que injusticia, sufrimiento y odio. Gaye parece haberse inspirado en la experiencia de su hermano, que pasó tres años en el ejército durante la guerra de Vietnam. ",1971,4,R.drawable.whatsgoing));
        canciones.add(new Canciones("Respect", "Aretha Franklin", "«Respect» (en español: «Respeto») es una canción escrita e interpretada originalmente por el artista estadounidense Otis Redding en 1965. La canción se convirtió en un éxito de 1967 y una canción insignia para la cantante de soul Aretha Franklin. La música en las dos versiones es significativamente diferente, y a través de algunos cambios en las letras, las historias contadas por las canciones tienen un sabor diferente. La versión de Redding es una súplica de un hombre desesperado, que le dará a su mujer todo lo que quiera. A él no le importará si ella lo hace mal, siempre y cuando reciba el debido respeto cuando traiga dinero a casa.1\u200B Sin embargo, la versión de Aretha Franklin es una declaración de una mujer fuerte y segura de sí misma, que sabe que tiene todo lo que su hombre quiere. Ella nunca lo hace mal, y exige su «Respect».2\u200B La versión de Franklin agrega el coro \"R-E-S-P-E-C-T\" y el estribillo de los cantantes de respaldo de \"Sock it to me, sock it to me to sock\"... \".\n" +
                "\n" +
                "La versión de Aretha fue un hito para el movimiento feminista, y a menudo se la considera una de las mejores canciones de la era de R&B, ganando dos premios Grammy en 1968 por \"Best Rhythm & Blues Recording\" y \"Best Rhythm & Blues Solo Vocal Performance, Female\", y fue incluido en el Grammy Hall of Fame en 1987. En 2002, la Biblioteca del Congreso de Estados Unidos honró la versión de Franklin agregándola al Registro Nacional de Grabaciones. Fue colocada en el número cinco en la lista de la revista Rolling Stone de \"Las 500 mejores canciones de todos los tiempos\".3\u200B También se incluyó en la lista de \"Canciones del siglo\", por la industria discográfica de América y el National Endowment for the Arts. Franklin incluyó una grabación en vivo en el álbum Aretha en París (1968). ",1967,5,R.drawable.respect));
        canciones.add(new Canciones("Good Vibrations", "The Beach Boys", "«Good Vibrations» es una canción escrita, compuesta y producida por Brian Wilson con letras de Mike Love e interpretada por The Beach Boys con Carl Wilson como vocalista principal. Fue publicada en sencillo el 10 de octubre de 1966 con el instrumental \"Let's Go Away For Awhile\" de Pet Sounds en el lado B. La canción se convirtió en todo un éxito tanto en su país como en el Reino Unido, alcanzando el número uno en ambos países y en otros cinco. Fue grabada durante las sesiones de Pet Sounds, pero no fue incluida en el álbum, sino que se editó como un sencillo con la idea de que no acompañe ningún álbum, aunque después se la consideró para el entonces futuro proyecto SMiLE. Cuando dicho álbum fue abandonado, \"Good Vibrations\" apareció en Smiley Smile. El 30 de marzo de 2016, la RIAA certificó disco de platino para \"Good Vibrations\" por vender un millón de copias, corrigiendo un error histórico por un cambio en el criterio de los galardones.2\u200B3\u200B\n" +
                "\n" +
                "Brian Wilson ha dicho que la génesis del título \"Good Vibrations\" vino de una anécdota que le contaba su madre sobre que los perros le ladran a ciertas personas en respuesta a sus \"malas vibraciones\". Fascinado con el concepto, Wilson se centró en la idea general del sistema límbico, o percepción extrasensorial, y desarrolló el resto de la canción.\n" +
                "\n" +
                "Sobre la base del enfoque de la producción en capas que había formulado anteriormente en Pet Sounds, Wilson grabó la canción de forma fragmentaria utilizando varios estudios de Los Ángeles a lo largo de ocho meses, lo que terminó en un mosaico cortado en pedazos con los episodios musicales marcados por varias tonos discordantes.4\u200B5\u200B6\u200B El publicista de la banda Derek Taylor llamó a la obra una \"sinfonía de bolsillo\", ya que cuenta con una exótica variedad de instrumentos inusuales para una canción pop de su tiempo, incluyendo el uso prominente de un arpa y un electroteremín, un instrumento desconocido para ese entonces, junto con instrumentos convencionales desempeñándose de manera novedosa en un éxito pop, como el violonchelo y el bajo.7\u200B8\u200B9\u200B10\u200B Sus costes de producción, situados entre 50.000 y 75.000 dólares de la época,11\u200B fueron los más elevados para una canción en aquel momento.12\u200B13\u200B\n" +
                "\n" +
                "Reconocida como una obra modernista de los años 60, a Wilson se le atribuye el uso del estudio de grabación como un instrumento más como parte fundamental de la composición de la canción, como en Pet Sounds. Su éxito le proporcionó a The Beach Boys una nominación al Grammy a la Mejor Interpretación Vocal Grupal en 1966, y la canción fue finalmente incluida en el Salón de la Fama del Grammy en 1994.14\u200B Es uno de los primeros clásicos de pop psicodélico de la época de la contracultura15\u200B16\u200B15\u200B que apareció en varias listas de las mejores canciones de todos los tiempos, siendo votada como el número uno en la lista de Mojo Top 100 Records of All Time chart in 199714\u200B, la sexta mejor canción en la lista de la revista Rolling Stone de las 500 mejores canciones de todos los tiempos, y ganó el cuarto puesto en la lista de las 20 mejores canciones de la revistaNew Musical Express.17\u200B. Además, \"Good Vibrations\" es parte del Salón de la Fama del Rock.13\u200B Según el sitio agregador de listas Acclaimed Music, es la cuarta canción más aclamada por los críticos de todos los tiempos.", 1966,6,R.drawable.goodvibrations));
        canciones.add(new Canciones("Johnny B. Goode", "Chuck Berry", "«Johnny B. Goode» es una canción del cantante y guitarrista estadounidense Chuck Berry que apareció por primera vez en su tercer álbum de estudio Chuck Berry Is on Top de 1959. El 12 de marzo de 1958 se publicó como sencillo a través de Chess Records y desde entonces ha sido su canción más reconocida a nivel mundial y, también, una de las más versionadas por otros artistas.1\u200B\n" +
                "\n" +
                "A los pocos días de ponerse a la venta llegó al segundo lugar de la lista R&B Singles y hasta la octava posición de los Billboard Hot 100, ambas de los Estados Unidos.2\u200B Desde hace años es reconocida como una de las primeras canciones del rock and roll y está situada en las listas de las mejores del rock tanto en libros y revistas como en páginas web. Una de ellas es la revista Rolling Stone, que la posicionó en el séptimo lugar de su lista de las 500 mejores canciones de todos los tiempos.3\u200B Según el sitio agregador de listas Acclaimed Music, es la 12.ª canción más aclamada por los críticos de todos los tiempos.",1958,7,R.drawable.johnnybgood));
        canciones.add(new Canciones("Hey Jude", "The Beatles", "«Hey Jude» es una canción de la banda británica de rock The Beatles, lanzada en agosto de 1968 como primer sencillo del sello discográfico de la formación, Apple Records. Acreditada a Lennon/McCartney, el tema es una balada que evolucionó a partir de «Hey Jules», canción que Paul McCartney escribió para consolar a Julian, el hijo de John Lennon, después del divorcio de sus padres. La canción arranca con una estructura de verso-puente basada en la interpretación vocal y el acompañamiento al piano de McCartney, a los cuales, según progresa la canción, se van añadiendo detalles complementarios que distinguen sus distintas secciones. Después de la cuarta estrofa, cambia a un final o coda que se desarrolla durante más de cuatro minutos, hasta terminar con un fade out.\n" +
                "\n" +
                "Con más de siete minutos de duración, fue en su tiempo la canción más larga de la historia en ocupar el Top 10 de las listas británicas de sencillos.5\u200B También pasó nueve semanas como n.º 1 en Estados Unidos —el tiempo más largo que ha permanecido una canción de The Beatles en la parte superior de las listas estadounidenses—. El sencillo ha vendido aproximadamente ocho millones de copias y se incluye en las listas de las mejores canciones de todos los tiempos. ",1968,8,R.drawable.jude));
        canciones.add(new Canciones("Smells Like Teen Spirit", "Nirvana", "«Smells Like Teen Spirit», es una canción de la banda estadounidense de grunge, Nirvana. Es la pista de apertura y sencillo principal del segundo álbum de la banda, Nevermind (1991), lanzado bajo el sello DGC Records. El inesperado éxito del tema llevaría a Nevermind a liderar diversas listas de éxitos musicales de todo el mundo a principios de 1992, un evento a menudo considerado como el punto en que el grunge entró al mainstream.4\u200B\n" +
                "\n" +
                "«Smells Like Teen Spirit» es considerada como uno de los himnos de la música de los años 1990, especialmente, como el himno de la Generación X.5\u200B6\u200B Lanzada en 1991, la canción llegó en una escena musical que veía el fin de la popularidad del hair metal de los años 1980. El tema, conocido por su famoso vídeo musical, habla sobre una imagen de rebeldía adolescente que fue muy bien acogida por su audiencia. Se considera casi con unanimidad a «Teen Spirit» como la canción más famosa del género grunge.\n" +
                "\n" +
                "Debido a su éxito masivo y a lo diferente que era de las composiciones de la escena mainstream del rock de los 80, dominada por bandas de glam metal o retro, «Smells Like Teen Spirit» revivió la popularidad del rock, abriendo la puerta al triunfo del grunge en los 90. Además, esta popularidad del grunge fue la responsable del renovado interés comercial por el rock alternativo,7\u200B que para mediados de los 90 se había convertido en un formato radiofónico dominante.\n" +
                "\n" +
                "«Smells Like Teen Spirit» ocupa el puesto número 9 en la lista de las 500 mejores canciones de todos los tiempos y en el puesto número 10 de las mejores canciones con guitarra, ambos de la revista Rolling Stone, así como el 37 de «Las 1000 mejores canciones de siempre» de la revista Q y elegida como la número 1 de «Las 100 mejores canciones de los 90» según el canal musical VH1",1991,9,R.drawable.smell));
        canciones.add(new Canciones("What'd I Say", "Ray Charles", "«What'd I Say» es una canción escrita por el músico Ray Charles. Después de otros éxitos, con esta canción finalmente Charles provocó un nuevo subgénero de R&B titulado soul, finalmente reuniendo todos los elementos que Charles había estado creando grabó «I Got a Woman» que sería otro gran éxito en las listas R&B. La revista Rolling Stone la colocó en el puesto n.º 10 en la lista de las 500 mejores canciones de todos los tiempos. ",1959,10,R.drawable.whatdisay));
        return canciones;
    }

}